version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - worker
      - beat
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: celery -A robot -l info
    volumes:
      - .:/code
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: celery -A robot beat -l info
    volumes:
      - .:/code
